### ISSUE TITLE
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'

### ISSUE THREAD

**Issue by anthropos9** [ultralytics/mkdocs#24]
Whenever I run `mkdocs build` with Ultrallytics configured as a plugin I get this error:
```
ERROR   -  Error building page 'index.md': unsupported operand type(s) for +: 'NoneType' and 'str'
Traceback (most recent call last):
  File "/DEV_DIRECTORY/essays/.venv/bin/mkdocs", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/DEV_DIRECTORY/essays/.venv/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/DEV_DIRECTORY/essays/.venv/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/DEV_DIRECTORY/essays/.venv/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/DEV_DIRECTORY/essays/.venv/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/DEV_DIRECTORY/essays/.venv/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/DEV_DIRECTORY/essays/.venv/lib/python3.11/site-packages/mkdocs/__main__.py", line 286, in build_command
    build.build(cfg, dirty=not clean)
  File "/DEV_DIRECTORY/essays/.venv/lib/python3.11/site-packages/mkdocs/commands/build.py", line 349, in build
    _build_page(
  File "/DEV_DIRECTORY/essays/.venv/lib/python3.11/site-packages/mkdocs/commands/build.py", line 235, in _build_page
    output = config.plugins.on_post_page(output, page=page, config=config)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/DEV_DIRECTORY/essays/.venv/lib/python3.11/site-packages/mkdocs/plugins.py", line 586, in on_post_page
    return self.run_event('post_page', output, page=page, config=config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/DEV_DIRECTORY/essays/.venv/lib/python3.11/site-packages/mkdocs/plugins.py", line 507, in run_event
    result = method(item, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/DEV_DIRECTORY/essays/.venv/lib/python3.11/site-packages/plugin/main.py", line 82, in on_post_page
    page_url = config['site_url'] + page.url.rstrip('/')
               ~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'

```
When I remove the plugin from the `mkdocs.yml` file the build works fine. 

I'm running Python 3.11.2 in a venv

This is my `mkdocs.yml` file:
```yaml
site_name: BetaFaith Essays
theme:
  name: material
  palette:

    # Palette toggle for light mode
    - scheme: default
      primary: blue grey
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: black
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.instant
    - navigation.sections
markdown_extensions:
  - footnotes
plugins:
  - ultralytics
```

And my `requirements.txt` file:
```
mkdocs
mkdocs-material
mkdocs-ultralytics-plugin

```

**Comment by glenn-jocher** [comment]
@anthropos9 thanks for the bug report! We will attempt to reproduce and push a fix for this soon.

**Comment by anthropos9** [comment]
@glenn-jocher that did it for me. Thanks for looking into it.

**Comment by glenn-jocher** [comment]
Woohoo awesome! Strongly suggest adding a `site_url` too though for the plugin to fully work.

**Comment by anthropos9** [comment]
Adding the `site_url` was my test. Works swimmingly. Thanks again.
